server:
  port: 9090

spring:
  application:
    name: 'gateway-service'
  zipkin:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: "http://netflix:eureka@localhost:8761/eureka"
