package com.learners.model;

public enum OrderEvent {

    CANCEL_ORDER, VALIDATE_ORDER, VALIDATION_SUCCESS, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_FAILED,
    ALLOCATION_NO_INVENTORY, PICK_UP
}
