server:
  port: 8087

spring:
  application:
    name: "inventory-failover-service"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: "config-server"
  config:
    import: "optional:configserver:"

app:
  config:
    default-inventory: 999
